export const FETCH_RESULTS = "FETCH_RESULTS";

export const UPDATE_SEARCH_KEYWORD = "UPDATE_SEARCH_KEYWORD";

export const UPDATE_XML_TAGS = "UPDATE_XML_TAGS";

export const FILTER_GENDER = "FILTER_GENDER";

export const FILTER_COUNTRY = "FILTER_COUNTRY";

export const FILTER_SORTBY = "FILTER_SORTBY";

export const FILTER_RESET = "FILTER_RESET"

export const FILTER_CONTINENT = "FILTER_CONTINENT";

export const FILTER_STATUS = "FILTER_STATUS";

export const ADD_SEARCH_HISTORY = "ADD_SEARCH_HISTORY";

export const RESET_SEARCH_HISTORY = "RESET_SEARCH_HISTORY";